#!/bin/sh

if [ `whoami` != 'admin' ]; then
	echo "task must be called as admin"
	exit 1
fi

export DATA="/usr/local/filebot-node/data"
export TASK="$1"

export JAVA_OPTS=`free | awk -vm=1024 -vp=0.7 '/Mem:/ {printf "-Xmx%dm", ($2*p)/m; exit}'` # set -Xmx to 0.7 of physical memory

echo "filebot @$DATA/task/$TASK.args" # log arguments

filebot @"$DATA/task/$TASK.args" 2>&1 | tee -a "$DATA/log/$TASK.log"

exit ${PIPESTATUS[0]} # return filebot exit code (and not tee exit code)
