#!/bin/sh


echo "
-------------------- Run $0 (PID: $$) -------------------- $(date)
"


export FILEBOT_NODE_HOST="127.0.0.1" # bind to local apache reverse proxy
export FILEBOT_NODE_AUTH="QNAP"

export FILEBOT_NODE_HTTP="YES"
export FILEBOT_NODE_HTTP_PORT="5452"

export USER="admin"                                                                                                          # set admin as filebot user
export JAVA_OPTS=$(awk '/MemTotal:/ { xmx = ($2*0.8)/1024; if (xmx < 1024) { printf "-Xmx%dm", xmx }; exit}' /proc/meminfo)  # set -Xmx to 0.8 of physical memory (on low-memory devices)

export FILEBOT_NODE_DATA="/opt/filebot-node/data"
export FILEBOT_TASK_CMD="/opt/filebot-node/task"

export FILEBOT_CMD="filebot"
export FILEBOT_CMD_CWD="$QPKG_DEFAULT_VOLUME"
export FILEBOT_CMD_UID=$(id -u $USER)
export FILEBOT_CMD_GID=$(cat /etc/group | grep 'administrators' | cut -d: -f3)                # cannot use `id -u $USER` because the result is 100:users but we need 101:administrators because users don't have execute permissions

export FILEBOT_NODE_CLIENT="client"


# sanity check
if [ -z "$FILEBOT_CMD_UID" ]; then
	echo "id -u $USER must not be empty"
	exit 1
fi


# nodejsv8 package comes with broken permissions, so we need to fix them here first
find /usr/local/bin -type l -name node -exec chmod +x {} +

# check $PATH
NODE="$(which node)"

# check QNAP packages
if [ ! -x "$NODE" ]; then
	NODE="$(find "$QPKG_DEFAULT_VOLUME"/.qpkg/{QDMS,nodejs*} -maxdepth 3 -type f -name node 2> /dev/null | head -n1)"
	echo "NODE=$NODE"
fi


# node: command not found
if [ ! -x "$NODE" ]; then
	WARN="Node.js is not installed. Please install Node.js in the App Center."
	# print warning to console log
	echo "$WARN"
	# send to QNAP notification center
	/sbin/log_tool -t2 -uSystem -p127.0.0.1 -mlocalhost -a "[FileBot Node] $WARN"
	# node: command not found
	exit 127
fi


# set working dir
cd "$QPKG_ROOT"

# --optimize_for_size (Enables optimizations which favor memory size over execution speed.)
exec "$NODE" --optimize_for_size "server/app.js"
