#!/bin/sh

# uninstall the initctl and firewall profiles only if package is uninstalled
if [ "$SYNOPKG_PKG_STATUS" != "UPGRADE" ]; then
	rm "/etc/init/$SYNOPKG_PKGNAME.conf"
	servicetool --remove-configure-file --package "$SYNOPKG_PKGNAME.sc"
fi

# remove /usr/local/[package] link
rm "/usr/local/$SYNOPKG_PKGNAME"

# remove log
rm "/var/log/upstart/$SYNOPKG_PKGNAME.log"

# return successfully
exit 0
