#!/bin/sh

# uninstall the initctl and firewall profiles only if package is uninstalled
if [ "$SYNOPKG_PKG_STATUS" != "UPGRADE" ]; then
	rm "/etc/init/$SYNOPKG_PKGNAME.conf"
	servicetool --remove-configure-file --package "$SYNOPKG_PKGNAME.sc"
fi

# return successfully
exit 0
