#!/bin/sh
FILEBOT_NODE_DATA="/var/packages/filebot-node/var"

# prepare log file permissions
touch "$FILEBOT_NODE_DATA/filebot.log"
chmod 666 "$FILEBOT_NODE_DATA/filebot.log"

# print notification
{
cat << EOF
<p style='color:#0090D9'>Note: If FileBot cannot access your media, please verify that user <strong>FileBot</strong> is granted permission in <strong>Control Panel</strong>.</p>
<ol>
	<li>Open <strong>Control Panel</strong> and select <strong>Shared Folder</strong></li>
	<li>Select the share that contains your media and click <strong>Edit</strong></li>
	<li>Click the <strong>Permissions</strong> tab</li>
	<li>Change the dropdown from <strong>Local Users</strong> to <strong>System internal user</strong></li>
	<li>Check the <strong>Read/Write</strong> checkbox for the <strong>FileBot</strong> user</li>
	<li>Click <strong>Save</strong> to confirm the new permissions</li>
	<li>Repeat steps 2-6 for each share you want FileBot to access</li>
</ol>
EOF
} >> "$SYNOPKG_TEMP_LOGFILE"

# return successfully
exit 0
