#!/bin/sh

case "$1" in
	start)
		"$SYNOPKG_PKGDEST/start" > "$SYNOPKG_PKGDEST/node.log" 2>&1 &
		exit $?
	;;

	stop)
		killall "$SYNOPKG_PKGNAME"
		exit $?
	;;

	status)
		ps | grep "$SYNOPKG_PKGNAME" | grep -v 'grep'
		exit $?
	;;

	log)
		echo "$SYNOPKG_PKGDEST/node.log"
		exit 0
	;;

	*)
		exit 1
	;;
esac
