#!/bin/sh

case "$1" in
	start)
		initctl start "$SYNOPKG_PKGNAME"
		exit 0
	;;

	stop)
		initctl stop "$SYNOPKG_PKGNAME"
		exit 0
	;;

	status)
		initctl status "$SYNOPKG_PKGNAME" | grep "running"
		exit $?
	;;

	log)
		echo "/var/log/upstart/$SYNOPKG_PKGDEST.log"
		exit 0
	;;

	*)
		exit 0
	;;
esac
