#!/bin/sh
FILEBOT_NODE_DATA="/var/packages/filebot-node/var"

# prepare log file permissions
touch "$FILEBOT_NODE_DATA/filebot.log"
chmod 666 "$FILEBOT_NODE_DATA/filebot.log"

# set -Xmx to 0.8 of physical memory (on low-memory devices)
if [ ! -f "$FILEBOT_NODE_DATA/environment.sh" ]; then
	JAVA_OPTS=$(awk '/MemTotal:/ { xmx = ($2*0.8)/1024; if (xmx < 1024) { printf "-Xmx%dm", xmx }; exit}' /proc/meminfo)
	echo "export JAVA_OPTS=$JAVA_OPTS" > "$FILEBOT_NODE_DATA/environment.sh"
fi

# print notification
{
cat << EOF
<p style="color: #0090D9; text-align: center; font-weight: bold;">NOTE</p>
<p style="color: #0090D9; margin: 1em 0em;">FileBot Node cannot access your files unless you explicitly grant <b>Read/Write</b> permissions.</p>
<ol style="list-style-type: decimal; list-style-position: inside;">
	<li>Open <b>Control Panel</b> and select <b>Shared Folder</b></li>
	<li>Select the share that contains your files and click <b>Edit</b></li>
	<li>Select <b>Permissions</b></li>
	<li>Change <b>Local users</b> to <b>System internal user</b></li>
	<li>Check <b>Read/Write</b> for <b>FileBot</b> and click <b>Save</b></li>
</ol>
EOF
} >> "$SYNOPKG_TEMP_LOGFILE"

# return successfully
exit 0
