#!/bin/sh


# require node
if ! which node; then
	echo "<p><strong>FileBot Node</strong> requires <strong>Node.js</strong>. Please install <strong>Node.js</strong> first.</p>" >> "$SYNOPKG_TEMP_LOGFILE"
	exit 1
fi


# return successfully
exit 0
