#!/bin/sh


case "$1" in
	start)
		"$SYNOPKG_PKGDEST/bin/filebot-node-start" > "$SYNOPKG_PKGVAR/filebot-node.log" 2>&1 & disown
		exit $?
	;;

	stop)
		killall -u "$(id -u)" -- "node"
		exit $?
	;;

	status)
		ps -u "$(id -u)" | grep "node"
		exit $?
	;;
esac
